### ISSUE TITLE
Rename context.yaml to metadata.yaml

### ISSUE THREAD

**Issue by nottrobin** [CanonicalLtd/documentation-builder#21]
context.yaml is just cryptic

**Comment by anthonydillon** [comment]
Should it not be METADATA.yaml so it is ignored in the build or are you not
expecting yaml files to be processed as pages?

**Comment by nottrobin** [comment]
No it just parser markdown files.

The reason for the upper case rule is because README.md, LICENSE.md, HACKING.md are standard patterns.

However, metadata.yaml is a far more common pattern than METADATA.yaml.

**Comment by nottrobin** [comment]
Fixed in 555ec7bc
