### ISSUE TITLE
received an unexpected http response code (500)

### ISSUE THREAD

**Issue by wjkennedy** [CanonicalLtd/documentation-builder#37]
sudo snap install documentation-builder
error: cannot perform the following tasks:
- Download snap "ubuntu-core" (423) from channel "stable" (received an unexpected http response code (500) when trying to download https://068ed04f23.site.internapcdn.net/download-snap/b8X2psL1ryVrPt5WEmpYiqfr5emixTd7_423.snap?t=2016-11-10T00:29:17Z&h=f7331e73d52512cfdc5fe7a6feb433ecd890c903)

**Comment by ycheng** [comment]
@wjkennedy I try to install it today and it works fine for me. not sure if you want to try it again.
