### ISSUE TITLE
Support the `versions` file

### ISSUE THREAD

**Issue by nottrobin** [CanonicalLtd/documentation-builder#5]
The `versions` file (e.g. [in maas-docs](https://github.com/canonicalltd/maas-docs/tree/master/versions)) should contain a list of branch names, one per line. The builder should build the documentation for each branch mentioned in the `versions` file under its own folder corresponding to the branch name. E.g.:

``` bash
$ cat versions
1.8
1.9
2.0
$ # run the builder
$ tree
.
├── build
│   ├── 1.8
│   │   └── en
│   │       └── index.html
│   ├── 1.9
│   │   └── en
│   │       └── index.html
│   └── 2.0
│       └── en
│           └── index.html
└── versions
```

However, we have to consider a few user stories here and how best to handle them:

- You have pulled down the repository and you want to build all the documentation exactly as it would be online (including versions)
- You want to build only the current branch - not the version branches
- You have pulled down the master branch as a zip, without the git repository. So there's a versions file but no way to find the version branches

I think either a `--versions` or `--no-versions` flag should help with the first two. For the final one, we might need to be a little clever about detecting whether version branches exist, and providing good informative error messages.

**Comment by evilnick** [comment]
I think using '--versions' - this will most often be automated etc, for writers use, we will generally only be building a single version 

yes, the third scenario is a little more problematic, but we should have version-checking logic anyhow i think (what if someone makes a mistake in the versions file and includes something that doesn't exist?)
