### ISSUE TITLE
Update to work with latest version of vanilla-docs-theme

### ISSUE THREAD

**Issue by barrymcgee** [CanonicalLtd/documentation-builder#51]

**Comment by nottrobin** [comment]
Pretty sure this is now on the latest version. As I write this, [the theme is at](https://github.com/vanilla-framework/vanilla-docs-theme/blob/3d4aec6ab24f820f59fff644fd499d1e101a8da4/package.json#L3) `1.3.4`, and that is the version that [the template is using](https://github.com/CanonicalLtd/documentation-builder/blob/master/ubuntudesign/documentation_builder/resources/template.html#L18).

Closing.
