### ISSUE TITLE
Write a generator for documentation markdown repositories

### ISSUE THREAD

**Issue by evilnick** [CanonicalLtd/documentation-builder#52]
It would be nice/cool if documentation-builder could generate the skeleton files it needs for a repo

**Comment by nottrobin** [comment]
I think we should implement this as a [yeoman generator](http://yeoman.io/generators/), as that's exactly what they're meant for (and we are planning to write generators for many of our other projects as well).

Then we should document how to use the generator in the official documentation-builder docs.

**Comment by nottrobin** [comment]
To do:

- Create new repository: `canonical-webteam/generator-canonical-documentation`: A [yeoman generator](http://yeoman.io/generators/)
- Document how to use the generator in [documentation-builder docs](https://github.com/CanonicalLtd/documentation-builder/tree/master/docs/en)

**Comment by nottrobin** [comment]
@evilnick Done! Take a look: https://github.com/canonical-webteam/generator-canonical-documentation

**Comment by evilnick** [comment]
Nice! Shame it wasn't done before I had to create all those new docs!

But good work anyway :)
