### ISSUE TITLE
Page <title> doesn't reflect content title

### ISSUE THREAD

**Issue by caldav** [CanonicalLtd/documentation-builder#58]
For a page named "content page" on a doc site named "doc site", I would expect the page title to be: "content page", "content page - doc site" or "doc site - content page", but it's always "doc site".  

This has a high impact on search results, giving every result the same title: https://docs.ubuntu.com/search?q=image&domain=docs.ubuntu.com%2Fcore

**Comment by nottrobin** [comment]
That is a very good point. I am not sure how that happened. You are absolutely right that the key reason for the `title` YAML frontmatter setting is for it to be used in the meta title. I'll see if I can fix this now.
