### ISSUE TITLE
Implement notifications/admonitions

### ISSUE THREAD

**Issue by evilnick** [CanonicalLtd/documentation-builder#64]
We should implement some tasteful design as a placeholder: at the moment Warnings etc are just styled as plain text.

**Comment by anthonydillon** [comment]
We could reinstate the `p-note` pattern for the time being:
 https://github.com/vanilla-framework/vanilla-docs-theme/commit/b95e0923fabe0712ceaeefe8dd184e832ab51e5f

**Comment by evilnick** [comment]
That also works for me

**Comment by nottrobin** [comment]
I've changed the title of this issue to providing the full implementation.

The notifications will be available in vanilla-docs-theme (as mentioned in https://github.com/vanilla-framework/vanilla-docs-theme/issues/28) as soon as https://github.com/vanilla-framework/vanilla-docs-theme/issues/29 is merged.

Building on the work done by @evilnick in #63 it is now relatively quick to make use of these notification styles to style up admonition blocks in the documentation. I am working on this now.

**Comment by nottrobin** [comment]
I've added support for generating notifications in #65.

As mentioned in https://github.com/vanilla-framework/vanilla-docs-theme/issues/28, this simply adds support for the existing set of [vanilla-framework notifications](https://docs.vanillaframework.io/en/patterns/notification), as we don't have any designs for anything else. It doesn't make any attempt to provide any other types to conform with any other "admonitions" specification.

I'm considering #65 to resolve this issue for now, so this will be closed when that is merged, but if anyone feels they need other functionality please mention it in another issue either here or on vanilla-docs-theme.
